//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiprimerMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCPruebasEntities : DbContext
    {
        public MVCPruebasEntities()
            : base("name=MVCPruebasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MVC_Cursos> MVC_Cursos { get; set; }
        public virtual DbSet<MVC_Empleados> MVC_Empleados { get; set; }
        public virtual DbSet<MVC_EmpleadosCursos> MVC_EmpleadosCursos { get; set; }
    }
}
