//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiprimerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVC_EmpleadosCursos
    {
        public int IdEmpleado { get; set; }
        public int IdCurso { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
    
        public virtual MVC_Cursos MVC_Cursos { get; set; }
        public virtual MVC_Empleados MVC_Empleados { get; set; }
        public virtual MVC_Empleados MVC_Empleados1 { get; set; }
        public virtual MVC_Empleados MVC_Empleados2 { get; set; }
    }
}
