//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiprimerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVC_Cursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVC_Cursos()
        {
            this.MVC_EmpleadosCursos = new HashSet<MVC_EmpleadosCursos>();
        }
    
        public int IdCurso { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
    
        public virtual MVC_Empleados MVC_Empleados { get; set; }
        public virtual MVC_Empleados MVC_Empleados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVC_EmpleadosCursos> MVC_EmpleadosCursos { get; set; }
    }
}
